### ISSUE TITLE
mvn命令后搜索报错.

### ISSUE THREAD

**Issue by mrdear** [kiwiflydream/DepQuery#1]
顺便问一下,数据是实时去抓取网页获取的吗?

安装使用报错如下:

Starting debug for 'DepQuery'

[2017-09-25 21:26:11][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from pyquery import PyQuery as pq
  File "/Users/niuli/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.90A9A8D2-359E-450F-AE81-A416995CFB15/pyquery/__init__.py", line 11, in <module>
    from .pyquery import PyQuery
  File "/Users/niuli/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.90A9A8D2-359E-450F-AE81-A416995CFB15/pyquery/pyquery.py", line 6, in <module>
    from .cssselectpatch import JQueryTranslator
  File "/Users/niuli/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.90A9A8D2-359E-450F-AE81-A416995CFB15/pyquery/cssselectpatch.py", line 7, in <module>
    from cssselect import xpath as cssselect_xpath
ImportError: No module named cssselect
[2017-09-25 21:26:11][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from pyquery import PyQuery as pq
  File "/Users/niuli/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.90A9A8D2-359E-450F-AE81-A416995CFB15/pyquery/__init__.py", line 11, in <module>
    from .pyquery import PyQuery
  File "/Users/niuli/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.90A9A8D2-359E-450F-AE81-A416995CFB15/pyquery/pyquery.py", line 6, in <module>
    from .cssselectpatch import JQueryTranslator
  File "/Users/niuli/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.90A9A8D2-359E-450F-AE81-A416995CFB15/pyquery/cssselectpatch.py", line 7, in <module>
    from cssselect import xpath as cssselect_xpath
ImportError: No module named cssselect
[2017-09-25 21:26:12][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from pyquery import PyQuery as pq
  File "/Users/niuli/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.90A9A8D2-359E-450F-AE81-A416995CFB15/pyquery/__init__.py", line 11, in <module>
    from .pyquery import PyQuery
  File "/Users/niuli/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.90A9A8D2-359E-450F-AE81-A416995CFB15/pyquery/pyquery.py", line 6, in <module>
    from .cssselectpatch import JQueryTranslator
  File "/Users/niuli/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.90A9A8D2-359E-450F-AE81-A416995CFB15/pyquery/cssselectpatch.py", line 7, in <module>
    from cssselect import xpath as cssselect_xpath
ImportError: No module named cssselect
[2017-09-25 21:26:12][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from pyquery import PyQuery as pq
  File "/Users/niuli/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.90A9A8D2-359E-450F-AE81-A416995CFB15/pyquery/__init__.py", line 11, in <module>
    from .pyquery import PyQuery
  File "/Users/niuli/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.90A9A8D2-359E-450F-AE81-A416995CFB15/pyquery/pyquery.py", line 6, in <module>
    from .cssselectpatch import JQueryTranslator
  File "/Users/niuli/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.90A9A8D2-359E-450F-AE81-A416995CFB15/pyquery/cssselectpatch.py", line 7, in <module>
    from cssselect import xpath as cssselect_xpath
ImportError: No module named cssselect

**Comment by kiwiflydream** [comment]
是抓取http://mvnrepository.com/  这个网站的，请问你用的是python2吗？

**Comment by mrdear** [comment]
mac自带的是py2.7,自己也装了3.6.不过默认用的应该是2.7吧

**Comment by kiwiflydream** [comment]
那就奇怪了，我也是用的默认的

**Comment by mrdear** [comment]
解决了,安装`cssselect`,`lxml`两个依赖包后就正常了,不过这种实时抓取解析速度确实有点慢.不过貌似也没什么好办法.

**Comment by kiwiflydream** [comment]
嗯，而且还是外国网站，我只缓存了图片，你可以缓存一下数据，毕竟这种版本信息变更不是很快
